// Self-contained HTML page that runs coder/ghostty-web (Ghostty's VT100 parser
// compiled to WASM, with an xterm.js-compatible API) inside the WebView and
// bridges it to React Native. The native side owns the WebSocket; this page
// only renders output and reports keystrokes/resize/scroll back up.
//
// ghostty-web is vendored from the upstream `main` branch (not the npm
// release): the IIFE library bundle and the ghostty-vt.wasm binary are inlined
// here as base64 (see src/vendor/, regenerated by scripts/build-ghostty-web).
//
// Bridge protocol
//   Native -> Web : window.onHostMessage(jsonString)
//                   { type: "reset" } | { type: "write", data }
//                   | { type: "fit" } | { type: "focus" } | { type: "blur" }
//                   | { type: "keepFocus", enabled }  // hold the soft keyboard open

//                   | { type: "scrollToBottom" }
//                   | { type: "scrollBy", deltaY }  // programmatic scroll (touch scroll/pan is handled in-page)
//                   | { type: "fontSize", value }
//                   | { type: "hostLayout", width, height }
//                   | { type: "session", cols, rows }  // mirror the host grid size
//                   | { type: "repaint" }  // force a full all-rows redraw (foreground)
//   Web -> Native : window.ReactNativeWebView.postMessage(JSON.stringify(...))
//                   { type: "ready", cols, rows }
//                   | { type: "input", data }
//                   | { type: "scroll", atBottom, canScroll }
//                   | { type: "log", message }

import { GHOSTTY_WEB_JS_B64 } from "./vendor/ghosttyWebBundle";
import { GHOSTTY_VT_WASM_B64 } from "./vendor/ghosttyWasm";

const THEME = {
  background: "#05070a",
  foreground: "#d1d9df",
  cursor: "#37bca5",
  cursorAccent: "#05070a",
  selectionBackground: "#263444",
  black: "#0e1218",
  red: "#e36c61",
  green: "#77b870",
  yellow: "#d9a850",
  blue: "#5b9ddf",
  magenta: "#b481cb",
  cyan: "#36b8c5",
  white: "#d1d9df",
  brightBlack: "#606a74",
  brightRed: "#f2897e",
  brightGreen: "#91cd8b",
  brightYellow: "#e8bd6d",
  brightBlue: "#76b3f1",
  brightMagenta: "#c898de",
  brightCyan: "#61cdd9",
  brightWhite: "#e6ecf1",
};

export const TERMINAL_HTML = `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover" />
    <style>
      html, body { margin: 0; height: 100%; background: ${THEME.background}; overflow: hidden; }
      #root {
        position: absolute; top: 0; left: 0; width: 100%; height: 100%;
        padding: 8px; box-sizing: border-box; overflow: hidden;
        /* pan-y (not none): Android WebView only raises the soft keyboard when
           its tap-gesture recognizer fires, which touch-action:none suppresses.
           Two-finger pinch still works — we preventDefault it in JS. */
        touch-action: pan-y; -webkit-user-select: none; user-select: none;
        background: ${THEME.background};
      }
      #root canvas { display: block; }
      #fallback { color: #89949d; font-family: -apple-system, system-ui, sans-serif; font-size: 13px; padding: 16px; }
    </style>
  </head>
  <body>
    <div id="boot"><div id="fallback">Loading terminal…</div></div>
    <div id="root"></div>
    <script>
      (function () {
        var theme = ${JSON.stringify(THEME)};
        var GW_B64 = "${GHOSTTY_WEB_JS_B64}";
        var WASM_B64 = "${GHOSTTY_VT_WASM_B64}";

        var pending = [];
        var ready = false;
        var term = null;
        var hostW = null;
        var hostH = null;
        var scrollAccum = 0;
        // While true, the host wants the soft keyboard held open: any blur of
        // ghostty's hidden textarea (Enter, taps on native chrome, IME quirks)
        // is answered with an immediate refocus. Toggled by "keepFocus".
        var keepFocus = false;
        // Desired ghostty grid size = the host session's cols/rows. We mirror the
        // host (the desktop owns the real terminal width) instead of reflowing the
        // PTY to the phone, then scale the whole grid to fit the screen.
        var gridCols = null;
        var gridRows = null;

        // User pinch-zoom / two-finger pan: zoom into the fit view and pan around
        // to see the rest of the session. baseScale stays 1 (always fit); zoom is
        // the user multiplier.
        var baseScale = 1;
        var zoom = 1;
        var panX = 0;
        var panY = 0;
        var ZOOM_MIN = 1;
        var ZOOM_MAX = 6;

        function resetZoom() { zoom = 1; panX = 0; panY = 0; }

        function clampPan() {
          var canvas = getCanvas();
          if (!canvas) { return; }
          var s = baseScale * zoom;
          var a = availSize();
          var contentW = canvas.offsetWidth * s;
          var contentH = canvas.offsetHeight * s;
          // Horizontal: center when the scaled content is narrower than the
          // viewport; otherwise clamp so an edge can't be dragged past the border.
          if (contentW <= a.w) { panX = (a.w - contentW) / 2; }
          else { panX = Math.max(a.w - contentW, Math.min(0, panX)); }
          // Vertical: top-align when it fits (a terminal grows downward); clamp
          // when zoomed in past the viewport.
          if (contentH <= a.h) { panY = 0; }
          else { panY = Math.max(a.h - contentH, Math.min(0, panY)); }
        }

        function applyCanvasTransform() {
          var canvas = getCanvas();
          if (!canvas) { return; }
          clampPan();
          var s = baseScale * zoom;
          canvas.style.transformOrigin = "0 0";
          canvas.style.transform =
            (s !== 1 || panX !== 0 || panY !== 0)
              ? "translate(" + panX + "px," + panY + "px) scale(" + s + ")"
              : "";
        }

        function pointDist(a, b) {
          var dx = a.clientX - b.clientX;
          var dy = a.clientY - b.clientY;
          return Math.sqrt(dx * dx + dy * dy);
        }

        // Does the scaled canvas overflow the viewport on either axis (i.e. is
        // there anywhere to pan)? True when zoomed in OR when the readability
        // floor made baseScale alone overflow the viewport.
        function contentOverflow() {
          var canvas = getCanvas();
          if (!canvas) { return { x: false, y: false }; }
          var s = baseScale * zoom;
          var a = availSize();
          return {
            x: canvas.offsetWidth * s > a.w + 1,
            y: canvas.offsetHeight * s > a.h + 1,
          };
        }

        // Gesture ownership: this page owns ALL terminal touch gestures. (The
        // native SwipeBar above the command bar owns session switching only —
        // it never scrolls the terminal.)
        //   - two fingers: pinch-zoom + pan
        //   - one finger, mostly vertical: scroll gesture anywhere on the
        //     surface (scrollback viewport / SGR wheel / damped arrows per
        //     screen mode) — like scrolling a normal page. While pinch-zoomed
        //     in, vertical drags pan instead (the drag is how you roam).
        //   - one finger, mostly horizontal: pans the canvas sideways when the
        //     floored/zoomed content overflows the viewport; inert otherwise
        //   - a tap (under the slop) is none of these: it must fall through so
        //     it lands on ghostty's stretched textarea and raises the keyboard.
        var TAP_SLOP_PX = 8;

        function installGestures() {
          var root = document.getElementById("root");
          if (!root || root.__gesturesInstalled) { return; }
          root.__gesturesInstalled = true;
          var pinch = null;
          // One-finger tracker. mode: "pending" until movement passes the tap
          // slop (so plain taps reach the textarea), then "pan" or "scroll".
          var single = null;

          root.addEventListener("touchstart", function (e) {
            if (e.touches.length === 2) {
              single = null; // a second finger promotes the gesture to pinch
              var rect = root.getBoundingClientRect();
              var t0 = e.touches[0], t1 = e.touches[1];
              pinch = {
                dist: pointDist(t0, t1) || 1,
                mx: (t0.clientX + t1.clientX) / 2 - rect.left,
                my: (t0.clientY + t1.clientY) / 2 - rect.top,
                zoom: zoom, panX: panX, panY: panY,
              };
              e.preventDefault();
              return;
            }
            if (e.touches.length === 1 && !pinch) {
              var t = e.touches[0];
              single = {
                id: t.identifier,
                startX: t.clientX, startY: t.clientY,
                lastX: t.clientX, lastY: t.clientY,
                mode: "pending",
              };
              // No preventDefault: a tap must stay a tap (keyboard focus).
            }
          }, { passive: false, capture: true });

          root.addEventListener("touchmove", function (e) {
            if (pinch && e.touches.length === 2) {
              var rect = root.getBoundingClientRect();
              var t0 = e.touches[0], t1 = e.touches[1];
              var newZoom = Math.max(ZOOM_MIN, Math.min(ZOOM_MAX, pinch.zoom * (pointDist(t0, t1) / pinch.dist)));
              var canvas = getCanvas();
              var originX = canvas ? canvas.offsetLeft : 0;
              var originY = canvas ? canvas.offsetTop : 0;
              var fx = pinch.mx - originX, fy = pinch.my - originY;
              var s0 = baseScale * pinch.zoom, s1 = baseScale * newZoom;
              var ratioS = s0 ? s1 / s0 : 1;
              var curMx = (t0.clientX + t1.clientX) / 2 - rect.left;
              var curMy = (t0.clientY + t1.clientY) / 2 - rect.top;
              // Keep the pinch focal point steady while zooming, then follow
              // the two-finger drag to pan.
              panX = (fx - ratioS * (fx - pinch.panX)) + (curMx - pinch.mx);
              panY = (fy - ratioS * (fy - pinch.panY)) + (curMy - pinch.my);
              zoom = newZoom;
              applyCanvasTransform();
              e.preventDefault();
              return;
            }
            if (!single || e.touches.length !== 1) { return; }
            var t2 = e.touches[0];
            if (t2.identifier !== single.id) { return; }
            if (single.mode === "pending") {
              var mx2 = t2.clientX - single.startX;
              var my2 = t2.clientY - single.startY;
              if (mx2 * mx2 + my2 * my2 < TAP_SLOP_PX * TAP_SLOP_PX) { return; }
              var o = contentOverflow();
              if (Math.abs(my2) >= Math.abs(mx2)) {
                // Vertical drags scroll the terminal from anywhere, like a
                // normal page — except while pinch-zoomed in, where the drag
                // roams the zoomed canvas instead.
                single.mode = (zoom > 1 && o.y) ? "pan" : "scroll";
              } else {
                // Horizontal drags only make sense as pans, and only when the
                // (floored/zoomed) content actually overflows sideways.
                single.mode = o.x ? "pan" : "scroll";
              }
            }
            var dx = t2.clientX - single.lastX;
            var dy = t2.clientY - single.lastY;
            single.lastX = t2.clientX;
            single.lastY = t2.clientY;
            if (single.mode === "pan") {
              panX += dx;
              panY += dy;
              applyCanvasTransform(); // clamps to content bounds
            } else {
              // deltaY > 0 means "show newer": dragging the finger up pulls
              // newer content into view (same convention as scrollByDelta).
              scrollByDelta(-dy);
            }
            e.preventDefault();
          }, { passive: false, capture: true });

          var endTouch = function (e) {
            if (!e.touches || e.touches.length < 2) { pinch = null; }
            if (!e.touches || e.touches.length === 0) { single = null; return; }
            if (single) {
              var alive = false;
              for (var i = 0; i < e.touches.length; i++) {
                if (e.touches[i].identifier === single.id) { alive = true; break; }
              }
              if (!alive) { single = null; }
            }
          };
          root.addEventListener("touchend", endTouch, { passive: true, capture: true });
          root.addEventListener("touchcancel", endTouch, { passive: true, capture: true });
        }

        function post(obj) {
          if (window.ReactNativeWebView) {
            window.ReactNativeWebView.postMessage(JSON.stringify(obj));
          }
        }

        function b64ToUtf8(b64) {
          var bin = atob(b64);
          var bytes = new Uint8Array(bin.length);
          for (var i = 0; i < bin.length; i++) { bytes[i] = bin.charCodeAt(i); }
          return new TextDecoder("utf-8").decode(bytes);
        }

        function fontSizeForWidth() {
          var width = hostW || window.innerWidth;
          return width <= 480 ? 13 : 14;
        }

        function readPixelDimension(value) {
          var number = Math.round(Number(value));
          if (!Number.isFinite(number) || number <= 0) { return null; }
          return Math.max(1, Math.min(number, 6000));
        }

        function clampDimension(value, min, max) {
          if (value === null || value === undefined || value === "") { return null; }
          var number = Math.floor(Number(value));
          if (!Number.isFinite(number)) { return null; }
          return Math.max(min, Math.min(number, max));
        }

        function metrics() {
          try {
            if (term && term.renderer && term.renderer.getMetrics) {
              var m = term.renderer.getMetrics();
              if (m && m.width > 0 && m.height > 0) { return m; }
            }
          } catch (e) {}
          var fs = fontSizeForWidth();
          return { width: fs * 0.6, height: fs * 1.3 };
        }

        function lineHeight() { return metrics().height || 16; }

        function getCanvas() {
          return document.getElementById("root").querySelector("canvas");
        }

        function availSize() {
          var root = document.getElementById("root");
          var pad = 16; // 8px padding both sides
          return {
            w: Math.max(80, (hostW || root.clientWidth || window.innerWidth) - pad),
            h: Math.max(80, (hostH || root.clientHeight || window.innerHeight) - pad),
          };
        }

        function applyHostLayoutStyle() {
          // Size #root to the host-provided box so mirror scaling uses the real
          // available area — e.g. shrinking when the keyboard reduces the
          // viewport.
          var root = document.getElementById("root");
          root.style.width = hostW ? hostW + "px" : "100%";
          root.style.height = hostH ? hostH + "px" : "100%";
        }

        function syncGrid() {
          // Mirror the host session's grid. The desktop owns the real terminal
          // width, and the snapshot/output bytes are laid out for that width — so
          // ghostty must render at exactly that many cols/rows or everything
          // re-wraps. We do NOT reflow the PTY down to the phone's width.
          if (!term || !gridCols || !gridRows) { return; }
          if (term.cols !== gridCols || term.rows !== gridRows) {
            try { term.resize(gridCols, gridRows); } catch (e) {}
          }
        }

        // Readability floor: never let a very wide host grid scale so far down
        // that the effective glyph size (fontSize * scale) drops below this.
        // When the floor wins over fit, the canvas overflows the viewport and
        // clampPan gives it panning slack — exactly like zoom overflow.
        var MIN_EFFECTIVE_FONT_PX = 10;

        function currentFontSize() {
          var fs = 0;
          try { fs = term && term.options ? Number(term.options.fontSize) : 0; } catch (e) {}
          return fs > 0 ? fs : fontSizeForWidth();
        }

        function minReadableScale() {
          return Math.min(1, MIN_EFFECTIVE_FONT_PX / currentFontSize());
        }

        function recomputeBaseScale() {
          // Scale the whole grid to fit the viewport on both axes, but never
          // upscale past 1:1 (a small grid renders native) and never shrink
          // below the readability floor (a huge grid overflows and pans
          // instead). Pinch-zoom goes above this to read; pan roams whenever
          // the content overflows.
          var canvas = getCanvas();
          if (!canvas) { baseScale = 1; return; }
          var cw = canvas.offsetWidth, ch = canvas.offsetHeight;
          var a = availSize();
          var sx = cw > 0 ? a.w / cw : 1;
          var sy = ch > 0 ? a.h / ch : 1;
          var fit = Math.min(1, sx, sy);
          baseScale = Math.min(1, Math.max(fit, minReadableScale()));
          if (!(baseScale > 0) || !isFinite(baseScale)) { baseScale = 1; }
        }

        function applyLayout() {
          if (!term) { return; }
          applyHostLayoutStyle();
          syncGrid();
          recomputeBaseScale();
          applyCanvasTransform();
          // Layout changes (keyboard open/close, cold-start settling) can land
          // while the canvas surface was just wiped; the dirty-row render loop
          // would then leave everything blank until fresh output arrives, so
          // always follow layout with a full redraw from the wasm grid.
          forceRepaint();
          setTimeout(reportScroll, 0);
        }

        function reportScroll() {
          if (!term || !term.wasmTerm) { return; }
          var sb = 0;
          try { sb = term.getScrollbackLength ? term.getScrollbackLength() : 0; } catch (e) {}
          var vy = 0;
          try { vy = term.getViewportY ? term.getViewportY() : 0; } catch (e) {}
          post({ type: "scroll", atBottom: vy === 0, canScroll: sb > 0 });
        }

        // Translate a pixel scroll delta (from the native pan gesture) into the
        // right kind of terminal input. deltaY > 0 means "show newer / scroll
        // down". Full-screen apps (Claude, Codex, vim, less) live on the
        // alternate screen where there is no scrollback to move, so we feed them
        // wheel/arrow input instead of trying to move a viewport that cannot
        // move.
        function scrollByDelta(deltaY) {
          if (!term || !term.wasmTerm || !Number.isFinite(deltaY) || deltaY === 0) { return; }
          var alt = false, mouse = false;
          try { alt = term.wasmTerm.isAlternateScreen && term.wasmTerm.isAlternateScreen(); } catch (e) {}
          try { mouse = term.wasmTerm.hasMouseTracking && term.wasmTerm.hasMouseTracking(); } catch (e) {}

          if (mouse) { sendWheel(deltaY); return; }
          if (alt) { sendArrows(deltaY); return; }

          // Normal screen: move the scrollback viewport directly (smooth).
          try { term.scrollLines(deltaY / lineHeight()); } catch (e) {}
          reportScroll();
        }

        // Mouse-tracking apps (Claude Code with mouse reporting on) get real SGR
        // wheel events; they know how to scroll themselves.
        function sendWheel(deltaY) {
          scrollAccum += deltaY;
          var lh = lineHeight();
          var steps = Math.trunc(scrollAccum / lh);
          if (steps === 0) { return; }
          scrollAccum -= steps * lh;
          var n = Math.min(Math.abs(steps), 8);
          var btn = steps > 0 ? 65 : 64; // SGR wheel down / up
          var col = Math.max(1, Math.min(term.cols, Math.floor(term.cols / 2) + 1));
          var row = Math.max(1, Math.min(term.rows, Math.floor(term.rows / 2) + 1));
          var out = "";
          for (var j = 0; j < n; j++) { out += "\\x1b[<" + btn + ";" + col + ";" + row + "M"; }
          post({ type: "input", data: out });
        }

        // Alt-screen apps WITHOUT mouse tracking (Claude/Codex prompt views,
        // menus): bare arrow keys move their selection / history, so pan
        // gestures must be conservative — heavily rate-limited, one arrow per
        // 24 logical px of accumulated pan, at most 3 arrows per message. The
        // sub-step remainder carries over; whole steps beyond the cap are
        // dropped so a fast fling can't queue a burst of stray arrows.
        var ARROW_STEP_PX = 24;
        var ARROW_MAX_STEPS = 3;
        var ARROW_MIN_INTERVAL_MS = 120;
        var arrowAccum = 0;
        var lastArrowAt = 0;

        function sendArrows(deltaY) {
          arrowAccum += deltaY;
          var steps = Math.trunc(arrowAccum / ARROW_STEP_PX);
          if (steps === 0) { return; }
          var now = Date.now();
          if (now - lastArrowAt < ARROW_MIN_INTERVAL_MS) { return; }
          lastArrowAt = now;
          arrowAccum -= steps * ARROW_STEP_PX;
          var n = Math.min(Math.abs(steps), ARROW_MAX_STEPS);
          var seq = steps > 0 ? "\\x1b[B" : "\\x1b[A";
          var out = "";
          for (var i = 0; i < n; i++) { out += seq; }
          post({ type: "input", data: out });
        }

        function forceRepaint() {
          // Force a full, all-rows repaint. ghostty-web's continuous render loop
          // only repaints *dirty* rows (its 2nd render arg = false); the 2D canvas
          // persists between frames. So when the canvas content is lost — the
          // requestAnimationFrame loop pauses while the WebView is backgrounded /
          // hidden, or a resize wipes the backing store — the un-dirtied rows are
          // left blank until the app happens to touch them again. Passing true as
          // the force flag redraws every row from the wasm grid, healing that.
          try {
            if (term && term.renderer && term.wasmTerm) {
              var op = (term.scrollbarOpacity != null) ? term.scrollbarOpacity : 0;
              term.renderer.render(term.wasmTerm, true, term.viewportY || 0, term, op);
            }
          } catch (e) {}
        }

        function hardRepaint() {
          // Rebuild the canvas backing store + 2D context, then force a full
          // redraw. A WebView returning from background can come back with its 2D
          // context reset to an identity transform (the devicePixelRatio scale
          // lost), which makes ghostty draw glyphs at the wrong scale — box-draw
          // lines turn into dashes, block glyphs into specks, whole rows look
          // blank. The renderer's resize() re-applies canvas.width = w*dpr +
          // ctx.scale(dpr) + textBaseline/align (the same setup a fresh load
          // does) without reloading the WASM or the grid, so it restores correct
          // glyph rendering where a bare re-render cannot.
          try {
            if (term && term.renderer && term.renderer.resize &&
                typeof term.cols === "number" && typeof term.rows === "number") {
              term.renderer.resize(term.cols, term.rows);
            }
          } catch (e) {}
          applyCanvasTransform();
          forceRepaint();
        }

        function scheduleFullRepaint() {
          // Heal now and again across a few frames: an Android WebView can return
          // from background a frame or two late, so a single pass can rebuild the
          // context before the surface has actually settled. Repeating ensures the
          // terminal ends fully painted rather than fragmented.
          hardRepaint();
          try { requestAnimationFrame(hardRepaint); } catch (e) {}
          setTimeout(hardRepaint, 80);
          setTimeout(hardRepaint, 300);
        }

        function dismissKeyboard() {
          // Dismiss the soft keyboard. ghostty's hidden textarea holds the
          // input connection, so term.blur() alone doesn't always tear it
          // down on Android — blur the textarea and the active element too.
          try {
            term.blur();
            if (term.textarea && term.textarea.blur) { term.textarea.blur(); }
            var activeEl = document.activeElement;
            if (activeEl && activeEl.blur && activeEl !== document.body) { activeEl.blur(); }
          } catch (e) {}
        }

        function handle(msg) {
          if (!term) { pending.push(msg); return; }
          switch (msg.type) {
            case "reset":
              try {
                term.reset();
                // term.reset() alone leaves the previous session's cells in
                // ghostty-web's grid, so they bleed through when switching to a
                // session with shorter lines. Drive an explicit hard clear through
                // the VT parser: leave the alternate screen (alt-screen TUIs like
                // Claude/Codex), erase scrollback + the whole screen, home cursor.
                term.write("\\x1b[?1049l\\x1b[3J\\x1b[2J\\x1b[H");
              } catch (e) {}
              resetZoom(); forceRepaint(); applyCanvasTransform();
              break;
            case "write": try { term.write(msg.data); } catch (e) {} setTimeout(reportScroll, 0); break;
            case "fit": applyLayout(); break;
            case "focus": try { term.focus(); } catch (e) {} break;
            case "blur":
              keepFocus = false;
              dismissKeyboard();
              break;
            case "keepFocus":
              keepFocus = !!msg.enabled;
              if (keepFocus) { try { term.focus(); } catch (e) {} }
              else { dismissKeyboard(); }
              break;
            case "scrollToBottom": try { term.scrollToBottom(); } catch (e) {} setTimeout(reportScroll, 0); break;
            case "scrollBy": scrollByDelta(Number(msg.deltaY)); break;
            case "fontSize":
              try { term.options.fontSize = Number(msg.value); } catch (e) {}
              applyLayout();
              break;
            case "hostLayout":
              hostW = readPixelDimension(msg.width);
              hostH = readPixelDimension(msg.height);
              applyLayout();
              break;
            case "session": {
              // The host tells us the session's real grid size; mirror it.
              var sc = clampDimension(msg.cols, 1, 1000);
              var sr = clampDimension(msg.rows, 1, 1000);
              if (sc) { gridCols = sc; }
              if (sr) { gridRows = sr; }
              applyLayout();
              break;
            }
            case "repaint":
              // App returned to foreground / surface became visible again — heal
              // any rows the dirty-only render loop left blank while we were away.
              scheduleFullRepaint();
              break;
          }
        }

        // Native -> Web entry point.
        window.onHostMessage = function (raw) {
          try { handle(typeof raw === "string" ? JSON.parse(raw) : raw); } catch (e) {}
        };

        function boot() {
          try {
            (0, eval)(b64ToUtf8(GW_B64));
          } catch (e) {
            document.getElementById("fallback").textContent = "Could not load terminal engine.";
            post({ type: "log", message: "ghostty-web bundle eval failed: " + (e && e.message) });
            return;
          }

          var GW = window.GhosttyWeb;
          if (!GW || !GW.Ghostty || !GW.Terminal) {
            document.getElementById("fallback").textContent = "Terminal engine missing.";
            post({ type: "log", message: "GhosttyWeb global not found" });
            return;
          }

          var wasmUrl = "data:application/wasm;base64," + WASM_B64;
          GW.Ghostty.load(wasmUrl).then(function (ghostty) {
            term = new GW.Terminal({
              ghostty: ghostty,
              cols: 80,
              rows: 24,
              cursorBlink: true,
              cursorStyle: "bar",
              fontFamily: '"Cascadia Mono", "Cascadia Code", "SFMono-Regular", Menlo, Consolas, ui-monospace, monospace',
              fontSize: fontSizeForWidth(),
              scrollback: 5000,
              theme: theme,
            });

            var bootEl = document.getElementById("boot");
            if (bootEl) { bootEl.remove(); }

            var root = document.getElementById("root");
            term.open(root);
            // Android WebViews only raise the soft keyboard when the user taps
            // *directly on an editable element* — a programmatic .focus() (which
            // is what tapping the canvas does) does nothing. So stretch ghostty's
            // hidden textarea to invisibly cover the terminal: a tap lands on it,
            // Android shows the keyboard, and input flows through ghostty as
            // usual. Kept fully transparent (no caret/text) so it's unseen.
            try {
              var ta = term.textarea;
              if (ta) {
                ta.style.position = "absolute";
                ta.style.left = "0";
                ta.style.top = "0";
                ta.style.width = "100%";
                ta.style.height = "100%";
                ta.style.margin = "0";
                ta.style.padding = "0";
                ta.style.border = "none";
                ta.style.outline = "none";
                ta.style.resize = "none";
                ta.style.opacity = "0";
                ta.style.clipPath = "none";
                ta.style.color = "transparent";
                ta.style.background = "transparent";
                ta.style.caretColor = "transparent";
                ta.style.zIndex = "2";
                ta.style.fontSize = "16px"; // avoid iOS focus-zoom
                ta.setAttribute("autocapitalize", "off");
                ta.setAttribute("autocorrect", "off");
                ta.setAttribute("autocomplete", "off");
                ta.setAttribute("spellcheck", "false");
                // Persistent keyboard: while the host holds keepFocus, any blur
                // (Enter's default handling, stray taps, IME dismiss attempts)
                // is undone a beat later so the soft keyboard never collapses.
                ta.addEventListener("blur", function () {
                  if (!keepFocus) { return; }
                  setTimeout(function () {
                    if (keepFocus) { try { term.focus(); } catch (e) {} }
                  }, 60);
                });
                // Hold-to-repeat backspace: Android IMEs auto-repeat a held
                // backspace by repeatedly deleting *content* before the caret
                // (deleteSurroundingText -> beforeinput "deleteContentBackward").
                // ghostty keeps this textarea empty, so GBoard has nothing to
                // delete: each tap falls back to one synthetic DEL keydown and a
                // hold never repeats. Park a run of sentinel spaces before the
                // caret so a held backspace always has content to chew. ghostty
                // preventDefault()s every delete it handles (still emitting DEL
                // 0x7f to the PTY), so the sentinel normally never drains; edits
                // that do land anyway (IME commits are not cancelable) are reset
                // below.
                var SENTINEL = "                                "; // 32 spaces
                var composing = false;
                var primeSentinel = function () {
                  if (composing) { return; }
                  if (ta.value !== SENTINEL) { ta.value = SENTINEL; }
                  if (ta.selectionStart !== SENTINEL.length || ta.selectionEnd !== SENTINEL.length) {
                    try { ta.setSelectionRange(SENTINEL.length, SENTINEL.length); } catch (e) {}
                  }
                };
                var primeSentinelSoon = function () { setTimeout(primeSentinel, 0); };
                ta.addEventListener("compositionstart", function () { composing = true; });
                ta.addEventListener("compositionend", function () { composing = false; primeSentinelSoon(); });
                // "input" only fires when an edit actually landed (handled ones
                // are preventDefault()'d) — refill so the reservoir never drains.
                ta.addEventListener("input", function () { if (!composing) { primeSentinelSoon(); } });
                // A tap can drop the caret mid-sentinel (backspace at offset 0
                // goes dead again) — re-park it once the tap's selection lands.
                ta.addEventListener("focus", primeSentinelSoon);
                ta.addEventListener("pointerup", primeSentinelSoon);
                primeSentinel();
              }
            } catch (e) {}
            try { term.blur(); } catch (e) {}
            window.__term = term; // exposed for diagnostics / smoke tests
            installGestures();

            term.onData(function (data) { post({ type: "input", data: data }); });
            // Note: no term.onResize -> post("resize") bridge. The phone is a
            // mirror — the grid only ever changes via syncGrid to match the
            // host's own session size, and it must NEVER drive the real PTY.
            term.onScroll(function () { reportScroll(); });

            // A real view resize (keyboard raise/dismiss resizing the WebView)
            // can reset the canvas 2D context outright — same failure mode as
            // returning from background — so beyond re-laying-out, heal with a
            // debounced full context rebuild once the resize burst settles.
            var resizeHealTimer = null;
            var onViewResize = function () {
              applyLayout();
              if (resizeHealTimer) { clearTimeout(resizeHealTimer); }
              resizeHealTimer = setTimeout(function () {
                resizeHealTimer = null;
                hardRepaint();
              }, 120);
            };
            window.addEventListener("resize", onViewResize);
            if (window.visualViewport) {
              window.visualViewport.addEventListener("resize", onViewResize);
            }

            // ghostty-web has no visibility handling of its own: its rAF render
            // loop pauses while the WebView is hidden/backgrounded and only ever
            // repaints dirty rows, so the surface can come back fragmented (mostly
            // blank with stray cells from the last frame). Force a full repaint
            // whenever the page becomes visible / regains focus again.
            document.addEventListener("visibilitychange", function () {
              if (document.visibilityState === "visible") { scheduleFullRepaint(); }
            });
            window.addEventListener("pageshow", scheduleFullRepaint);
            window.addEventListener("focus", scheduleFullRepaint);

            ready = true;
            for (var i = 0; i < pending.length; i++) { handle(pending[i]); }
            pending = [];

            applyLayout();
            setTimeout(function () {
              applyLayout();
              post({ type: "ready", cols: term.cols, rows: term.rows });
              reportScroll();
            }, 60);
          }).catch(function (err) {
            document.getElementById("fallback").textContent = "Terminal engine failed to start.";
            post({ type: "log", message: "Ghostty.load failed: " + (err && err.message) });
          });
        }

        if (document.readyState === "complete") {
          boot();
        } else {
          window.addEventListener("load", boot);
        }
      })();
    </script>
  </body>
</html>`;
