// Self-contained HTML page that runs coder/ghostty-web (Ghostty's VT100 parser
// compiled to WASM, with an xterm.js-compatible API) inside the WebView and
// bridges it to React Native. The native side owns the WebSocket; this page
// only renders output and reports keystrokes/resize/scroll back up.
//
// ghostty-web is vendored from the upstream `main` branch (not the npm
// release): the IIFE library bundle and the ghostty-vt.wasm binary are inlined
// here as base64 (see src/vendor/, regenerated by scripts/build-ghostty-web).
//
// Bridge protocol
//   Native -> Web : window.onHostMessage(jsonString)
//                   { type: "reset" } | { type: "write", data }
//                   | { type: "fit" } | { type: "focus" } | { type: "blur" }
//                   | { type: "scrollToBottom" } | { type: "scrollBy", deltaY }
//                   | { type: "fontSize", value }
//                   | { type: "hostLayout", width, height }
//                   | { type: "keyboardInset", height }  // shift view up, don't resize
//                   | { type: "session" }  // re-fit on the active session changing
//   Web -> Native : window.ReactNativeWebView.postMessage(JSON.stringify(...))
//                   { type: "ready", cols, rows }
//                   | { type: "input", data }
//                   | { type: "resize", cols, rows }  // fit mode only
//                   | { type: "viewport", cols, rows }
//                   | { type: "scroll", atBottom, canScroll }
//                   | { type: "log", message }

import { GHOSTTY_WEB_JS_B64 } from "./vendor/ghosttyWebBundle";
import { GHOSTTY_VT_WASM_B64 } from "./vendor/ghosttyWasm";

const THEME = {
  background: "#05070a",
  foreground: "#d1d9df",
  cursor: "#37bca5",
  cursorAccent: "#05070a",
  selectionBackground: "#263444",
  black: "#0e1218",
  red: "#e36c61",
  green: "#77b870",
  yellow: "#d9a850",
  blue: "#5b9ddf",
  magenta: "#b481cb",
  cyan: "#36b8c5",
  white: "#d1d9df",
  brightBlack: "#606a74",
  brightRed: "#f2897e",
  brightGreen: "#91cd8b",
  brightYellow: "#e8bd6d",
  brightBlue: "#76b3f1",
  brightMagenta: "#c898de",
  brightCyan: "#61cdd9",
  brightWhite: "#e6ecf1",
};

export const TERMINAL_HTML = `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover" />
    <style>
      html, body { margin: 0; height: 100%; background: ${THEME.background}; overflow: hidden; }
      #root {
        position: absolute; top: 0; left: 0; width: 100%; height: 100%;
        padding: 8px; box-sizing: border-box; overflow: hidden;
        /* pan-y (not none): Android WebView only raises the soft keyboard when
           its tap-gesture recognizer fires, which touch-action:none suppresses.
           Two-finger pinch still works — we preventDefault it in JS. */
        touch-action: pan-y; -webkit-user-select: none; user-select: none;
        background: ${THEME.background};
      }
      #root canvas { display: block; }
      #fallback { color: #89949d; font-family: -apple-system, system-ui, sans-serif; font-size: 13px; padding: 16px; }
    </style>
  </head>
  <body>
    <div id="boot"><div id="fallback">Loading terminal…</div></div>
    <div id="root"></div>
    <script>
      (function () {
        var theme = ${JSON.stringify(THEME)};
        var GW_B64 = "${GHOSTTY_WEB_JS_B64}";
        var WASM_B64 = "${GHOSTTY_VT_WASM_B64}";

        var pending = [];
        var ready = false;
        var term = null;
        var fit = null;
        var hostW = null;
        var hostH = null;
        var scrollAccum = 0;

        // User pinch-zoom / two-finger pan: zoom into the fit view and pan around
        // to see the rest of the session. baseScale stays 1 (always fit); zoom is
        // the user multiplier.
        var baseScale = 1;
        var zoom = 1;
        var panX = 0;
        var panY = 0;
        var kbInset = 0;   // px the keyboard occludes at the bottom; shifts the view up
        var ZOOM_MIN = 1;
        var ZOOM_MAX = 6;

        function resetZoom() { zoom = 1; panX = 0; panY = 0; }

        function clampPan() {
          var canvas = getCanvas();
          if (!canvas) { return; }
          var s = baseScale * zoom;
          var a = availSize();
          var contentW = canvas.offsetWidth * s;
          var contentH = canvas.offsetHeight * s;
          var minX = Math.min(0, a.w - contentW);
          var minY = Math.min(0, a.h - contentH);
          panX = Math.max(minX, Math.min(0, panX));
          panY = Math.max(minY, Math.min(0, panY));
        }

        function applyCanvasTransform() {
          var canvas = getCanvas();
          if (!canvas) { return; }
          clampPan();
          var s = baseScale * zoom;
          // Shift the whole view up by the keyboard inset so the bottom (the
          // active prompt / TUI input) sits above the keyboard, instead of
          // shrinking the terminal to make room.
          var ty = panY - kbInset;
          canvas.style.transformOrigin = "0 0";
          canvas.style.transform =
            (s !== 1 || panX !== 0 || ty !== 0)
              ? "translate(" + panX + "px," + ty + "px) scale(" + s + ")"
              : "";
        }

        function pointDist(a, b) {
          var dx = a.clientX - b.clientX;
          var dy = a.clientY - b.clientY;
          return Math.sqrt(dx * dx + dy * dy);
        }

        // Two-finger pinch-zoom + pan. Single-finger gestures are owned by the
        // native side (scroll / session switch / tap-to-focus); two-finger ones
        // are left for this page (the native PanResponder ignores multi-touch).
        function installGestures() {
          var root = document.getElementById("root");
          if (!root || root.__gesturesInstalled) { return; }
          root.__gesturesInstalled = true;
          var pinch = null;

          root.addEventListener("touchstart", function (e) {
            if (e.touches.length === 2) {
              var rect = root.getBoundingClientRect();
              var t0 = e.touches[0], t1 = e.touches[1];
              pinch = {
                dist: pointDist(t0, t1) || 1,
                mx: (t0.clientX + t1.clientX) / 2 - rect.left,
                my: (t0.clientY + t1.clientY) / 2 - rect.top,
                zoom: zoom, panX: panX, panY: panY,
              };
              e.preventDefault();
            }
          }, { passive: false, capture: true });

          root.addEventListener("touchmove", function (e) {
            if (!pinch || e.touches.length !== 2) { return; }
            var rect = root.getBoundingClientRect();
            var t0 = e.touches[0], t1 = e.touches[1];
            var newZoom = Math.max(ZOOM_MIN, Math.min(ZOOM_MAX, pinch.zoom * (pointDist(t0, t1) / pinch.dist)));
            var canvas = getCanvas();
            var originX = canvas ? canvas.offsetLeft : 0;
            var originY = canvas ? canvas.offsetTop : 0;
            var fx = pinch.mx - originX, fy = pinch.my - originY;
            var s0 = baseScale * pinch.zoom, s1 = baseScale * newZoom;
            var ratioS = s0 ? s1 / s0 : 1;
            var curMx = (t0.clientX + t1.clientX) / 2 - rect.left;
            var curMy = (t0.clientY + t1.clientY) / 2 - rect.top;
            // Keep the pinch focal point steady while zooming, then follow the
            // two-finger drag to pan.
            panX = (fx - ratioS * (fx - pinch.panX)) + (curMx - pinch.mx);
            panY = (fy - ratioS * (fy - pinch.panY)) + (curMy - pinch.my);
            zoom = newZoom;
            applyCanvasTransform();
            e.preventDefault();
          }, { passive: false, capture: true });

          var endPinch = function (e) {
            if (!e.touches || e.touches.length < 2) { pinch = null; }
          };
          root.addEventListener("touchend", endPinch, { passive: true, capture: true });
          root.addEventListener("touchcancel", endPinch, { passive: true, capture: true });
        }

        function post(obj) {
          if (window.ReactNativeWebView) {
            window.ReactNativeWebView.postMessage(JSON.stringify(obj));
          }
        }

        function b64ToUtf8(b64) {
          var bin = atob(b64);
          var bytes = new Uint8Array(bin.length);
          for (var i = 0; i < bin.length; i++) { bytes[i] = bin.charCodeAt(i); }
          return new TextDecoder("utf-8").decode(bytes);
        }

        function fontSizeForWidth() {
          var width = hostW || window.innerWidth;
          return width <= 480 ? 13 : 14;
        }

        function readPixelDimension(value) {
          var number = Math.round(Number(value));
          if (!Number.isFinite(number) || number <= 0) { return null; }
          return Math.max(1, Math.min(number, 6000));
        }

        function clampDimension(value, min, max) {
          if (value === null || value === undefined || value === "") { return null; }
          var number = Math.floor(Number(value));
          if (!Number.isFinite(number)) { return null; }
          return Math.max(min, Math.min(number, max));
        }

        function metrics() {
          try {
            if (term && term.renderer && term.renderer.getMetrics) {
              var m = term.renderer.getMetrics();
              if (m && m.width > 0 && m.height > 0) { return m; }
            }
          } catch (e) {}
          var fs = fontSizeForWidth();
          return { width: fs * 0.6, height: fs * 1.3 };
        }

        function lineHeight() { return metrics().height || 16; }

        function getCanvas() {
          return document.getElementById("root").querySelector("canvas");
        }

        function availSize() {
          var root = document.getElementById("root");
          var pad = 16; // 8px padding both sides
          return {
            w: Math.max(80, (hostW || root.clientWidth || window.innerWidth) - pad),
            h: Math.max(80, (hostH || root.clientHeight || window.innerHeight) - pad),
          };
        }

        function reportViewport() {
          // Readable fit size for the current host layout (used by the native
          // side when this view is the sizing authority).
          var a = availSize();
          var m = metrics();
          var cols = clampDimension(Math.floor(a.w / m.width), 20, 400);
          var rows = clampDimension(Math.floor(a.h / m.height), 8, 200);
          if (cols && rows) { post({ type: "viewport", cols: cols, rows: rows }); }
        }

        function applyHostLayoutStyle() {
          // Size #root to the host-provided box so FitAddon (which measures
          // #root) and mirror scaling both use the real available area — e.g.
          // shrinking when the keyboard reduces the viewport.
          var root = document.getElementById("root");
          root.style.width = hostW ? hostW + "px" : "100%";
          root.style.height = hostH ? hostH + "px" : "100%";
        }

        function applyLayout() {
          if (!term) { return; }
          applyHostLayoutStyle();
          // Always fit: reflow the terminal to the host box. FitAddon's onResize is
          // the single authority for the size we forward. Use pinch-zoom + pan to
          // inspect more than fits.
          if (fit) {
            try { fit.fit(); } catch (e) {}
          }
          baseScale = 1;
          applyCanvasTransform();
          setTimeout(reportScroll, 0);
        }

        function reportScroll() {
          if (!term || !term.wasmTerm) { return; }
          var sb = 0;
          try { sb = term.getScrollbackLength ? term.getScrollbackLength() : 0; } catch (e) {}
          var vy = 0;
          try { vy = term.getViewportY ? term.getViewportY() : 0; } catch (e) {}
          post({ type: "scroll", atBottom: vy === 0, canScroll: sb > 0 });
        }

        // Translate a pixel scroll delta (from the native pan gesture) into the
        // right kind of terminal input. deltaY > 0 means "show newer / scroll
        // down". Full-screen apps (Claude, Codex, vim, less) live on the
        // alternate screen where there is no scrollback to move, so we feed them
        // wheel/arrow input instead of trying to move a viewport that cannot
        // move.
        function scrollByDelta(deltaY) {
          if (!term || !term.wasmTerm || !Number.isFinite(deltaY) || deltaY === 0) { return; }
          var alt = false, mouse = false;
          try { alt = term.wasmTerm.isAlternateScreen && term.wasmTerm.isAlternateScreen(); } catch (e) {}
          try { mouse = term.wasmTerm.hasMouseTracking && term.wasmTerm.hasMouseTracking(); } catch (e) {}

          if (mouse) { sendDiscrete(deltaY, "mouse"); return; }
          if (alt) { sendDiscrete(deltaY, "arrow"); return; }

          // Normal screen: move the scrollback viewport directly (smooth).
          try { term.scrollLines(deltaY / lineHeight()); } catch (e) {}
          reportScroll();
        }

        function sendDiscrete(deltaY, kind) {
          scrollAccum += deltaY;
          var lh = lineHeight();
          var steps = Math.trunc(scrollAccum / lh);
          if (steps === 0) { return; }
          scrollAccum -= steps * lh;
          var n = Math.min(Math.abs(steps), 8);
          var out = "";
          if (kind === "arrow") {
            var seq = steps > 0 ? "\\x1b[B" : "\\x1b[A";
            for (var i = 0; i < n; i++) { out += seq; }
          } else {
            var btn = steps > 0 ? 65 : 64; // SGR wheel down / up
            var col = Math.max(1, Math.min(term.cols, Math.floor(term.cols / 2) + 1));
            var row = Math.max(1, Math.min(term.rows, Math.floor(term.rows / 2) + 1));
            for (var j = 0; j < n; j++) { out += "\\x1b[<" + btn + ";" + col + ";" + row + "M"; }
          }
          if (out) { post({ type: "input", data: out }); }
        }

        function clearCanvas() {
          // Wipe the canvas to the background colour before a repaint. On real
          // GPU-backed Android WebViews, term.reset() + a forced re-render don't
          // always flush blanked cells, so the previous session's frame bleeds
          // through when switching to a session with less content. Painting the
          // backing store directly clears those stale pixels. No-op for a WebGL
          // canvas (getContext('2d') returns null), where forceRepaint() covers it.
          try {
            var canvas = getCanvas();
            if (!canvas) { return; }
            var ctx = canvas.getContext("2d");
            if (ctx) {
              ctx.setTransform(1, 0, 0, 1, 0, 0);
              ctx.fillStyle = theme.background;
              ctx.fillRect(0, 0, canvas.width, canvas.height);
            } else {
              // ghostty-web renders via WebGL, where getContext('2d') is null.
              // Reassigning the canvas size resets (clears) the drawing buffer
              // without dropping GL programs/textures; forceRepaint() redraws.
              canvas.width = canvas.width;
            }
          } catch (e) {}
        }

        function forceRepaint() {
          // term.reset() clears the canvas, but on some GPU-backed WebView
          // canvases a bare clearRect isn't flushed until something draws — which
          // is why a stale frame from the previous session can linger until new
          // output arrives. Force a full synchronous repaint of the (now blank)
          // terminal so the switch is clean immediately.
          try {
            if (term && term.renderer && term.wasmTerm) {
              term.renderer.render(term.wasmTerm, true, term.viewportY || 0, term);
            }
          } catch (e) {}
        }

        function handle(msg) {
          if (!term) { pending.push(msg); return; }
          switch (msg.type) {
            case "reset":
              try {
                term.reset();
                // term.reset() alone leaves the previous session's cells in
                // ghostty-web's grid, so they bleed through when switching to a
                // session with shorter lines. Drive an explicit hard clear through
                // the VT parser: leave the alternate screen (alt-screen TUIs like
                // Claude/Codex), erase scrollback + the whole screen, home cursor.
                term.write("\\x1b[?1049l\\x1b[3J\\x1b[2J\\x1b[H");
              } catch (e) {}
              resetZoom(); clearCanvas(); forceRepaint(); applyCanvasTransform();
              break;
            case "write": try { term.write(msg.data); } catch (e) {} setTimeout(reportScroll, 0); break;
            case "fit": applyLayout(); break;
            case "focus": try { term.focus(); } catch (e) {} break;
            case "blur":
              // Dismiss the soft keyboard. ghostty's hidden textarea holds the
              // input connection, so term.blur() alone doesn't always tear it
              // down on Android — blur the textarea and the active element too.
              try {
                term.blur();
                if (term.textarea && term.textarea.blur) { term.textarea.blur(); }
                var activeEl = document.activeElement;
                if (activeEl && activeEl.blur && activeEl !== document.body) { activeEl.blur(); }
              } catch (e) {}
              break;
            case "scrollToBottom": try { term.scrollToBottom(); } catch (e) {} setTimeout(reportScroll, 0); break;
            case "scrollBy": scrollByDelta(Number(msg.deltaY)); break;
            case "fontSize":
              try { term.options.fontSize = Number(msg.value); } catch (e) {}
              applyLayout();
              break;
            case "hostLayout":
              hostW = readPixelDimension(msg.width);
              hostH = readPixelDimension(msg.height);
              applyLayout();
              break;
            case "keyboardInset": {
              var kb = Number(msg.height);
              kbInset = (Number.isFinite(kb) && kb > 0) ? Math.min(kb, 4000) : 0;
              applyCanvasTransform();
              break;
            }
            case "session":
              applyLayout();
              break;
          }
        }

        // Native -> Web entry point.
        window.onHostMessage = function (raw) {
          try { handle(typeof raw === "string" ? JSON.parse(raw) : raw); } catch (e) {}
        };

        function boot() {
          try {
            (0, eval)(b64ToUtf8(GW_B64));
          } catch (e) {
            document.getElementById("fallback").textContent = "Could not load terminal engine.";
            post({ type: "log", message: "ghostty-web bundle eval failed: " + (e && e.message) });
            return;
          }

          var GW = window.GhosttyWeb;
          if (!GW || !GW.Ghostty || !GW.Terminal) {
            document.getElementById("fallback").textContent = "Terminal engine missing.";
            post({ type: "log", message: "GhosttyWeb global not found" });
            return;
          }

          var wasmUrl = "data:application/wasm;base64," + WASM_B64;
          GW.Ghostty.load(wasmUrl).then(function (ghostty) {
            term = new GW.Terminal({
              ghostty: ghostty,
              cols: 80,
              rows: 24,
              cursorBlink: true,
              cursorStyle: "bar",
              fontFamily: '"Cascadia Mono", "Cascadia Code", "SFMono-Regular", Menlo, Consolas, ui-monospace, monospace',
              fontSize: fontSizeForWidth(),
              scrollback: 5000,
              theme: theme,
            });

            var bootEl = document.getElementById("boot");
            if (bootEl) { bootEl.remove(); }

            var root = document.getElementById("root");
            term.open(root);
            // Android WebViews only raise the soft keyboard when the user taps
            // *directly on an editable element* — a programmatic .focus() (which
            // is what tapping the canvas does) does nothing. So stretch ghostty's
            // hidden textarea to invisibly cover the terminal: a tap lands on it,
            // Android shows the keyboard, and input flows through ghostty as
            // usual. Kept fully transparent (no caret/text) so it's unseen.
            try {
              var ta = term.textarea;
              if (ta) {
                ta.style.position = "absolute";
                ta.style.left = "0";
                ta.style.top = "0";
                ta.style.width = "100%";
                ta.style.height = "100%";
                ta.style.margin = "0";
                ta.style.padding = "0";
                ta.style.border = "none";
                ta.style.outline = "none";
                ta.style.resize = "none";
                ta.style.opacity = "0";
                ta.style.clipPath = "none";
                ta.style.color = "transparent";
                ta.style.background = "transparent";
                ta.style.caretColor = "transparent";
                ta.style.zIndex = "2";
                ta.style.fontSize = "16px"; // avoid iOS focus-zoom
                ta.setAttribute("autocapitalize", "off");
                ta.setAttribute("autocorrect", "off");
                ta.setAttribute("autocomplete", "off");
                ta.setAttribute("spellcheck", "false");
              }
            } catch (e) {}
            try { term.blur(); } catch (e) {}
            window.__term = term; // exposed for diagnostics / smoke tests
            installGestures();

            if (GW.FitAddon) {
              fit = new GW.FitAddon();
              term.loadAddon(fit);
            }

            term.onData(function (data) { post({ type: "input", data: data }); });
            term.onResize(function (size) {
              post({ type: "resize", cols: size.cols, rows: size.rows });
            });
            term.onScroll(function () { reportScroll(); });

            window.addEventListener("resize", function () { applyLayout(); });
            if (window.visualViewport) {
              window.visualViewport.addEventListener("resize", function () { applyLayout(); });
            }

            ready = true;
            for (var i = 0; i < pending.length; i++) { handle(pending[i]); }
            pending = [];

            applyLayout();
            setTimeout(function () {
              applyLayout();
              post({ type: "ready", cols: term.cols, rows: term.rows });
              reportScroll();
            }, 60);
          }).catch(function (err) {
            document.getElementById("fallback").textContent = "Terminal engine failed to start.";
            post({ type: "log", message: "Ghostty.load failed: " + (err && err.message) });
          });
        }

        if (document.readyState === "complete") {
          boot();
        } else {
          window.addEventListener("load", boot);
        }
      })();
    </script>
  </body>
</html>`;
